root: true
env:
    node: true
    browser: true
extends:
    - brainbits-typescript
parserOptions:
    project: ./tsconfig.json
rules:
    class-methods-use-this: [off]
    no-underscore-dangle: [off]

